spring.application.name=SolicitacaoAnaliseCliente
spring.mongodb.uri=mongodb://localhost:27017/analisecliente?serverSelectionTimeoutMS=3000&connectTimeoutMS=3000
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest